name: 'nyc_taxi_production'
version: '1.0.0'


profile: 'nyc_taxi_production'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"


seeds:
  nyc_taxi_production:
    +column_types:
      LocationID: integer
      Borough: varchar(100)
      Zone: varchar(255)
      service_zone: varchar(100)


models:
  nyc_taxi_production:
    
    staging:
      +materialized: view
      +schema: staging
    
    
    marts:
      +materialized: table
      +schema: core